### ISSUE TITLE
Fix sending error in TestPostProductEvent

### ISSUE THREAD

**Issue by havardf** [metno/go-mms#10]
Seems the error is due to a bug in gochan.New() in the github.com/cloudevents/sdk-go/v2/protocol/gochan package.

The error manifests itself by the error message: "Sender has not been set." As in, the gochan.New() client has not a functioning Send mechanism?

**Comment by johtoblan** [comment]
This works:
```
temp := gochan.New()
temp.Send(context.Background(), nil)
c, err := cloudevents.NewClient(temp)
```

So the gochan.New() has functioning send.

Error seems to arise when 

```
c, err := cloudevents.NewClient(temp)

log.Printf("%T\n", temp)
log.Printf("%T\n", c)

log.Printf("%+v\n", temp)
log.Printf("%+v\n", c)
```
since this returns a *client.ceClient-struct with a receiver (not a sender), but temp is a *gochan.SendReceiver with a working send-method.

So for some reason in cloudevents.NewClient(temp) [found here](https://github.com/cloudevents/sdk-go/blob/master/v2/client/client.go) (Aliased as NewClient from client.New() ) :

```
// Not evaluated as True
if p, ok := obj.(protocol.Sender); ok {
		c.sender = p
}
// Evaluated as True
if p, ok := obj.(protocol.Receiver); ok {
	c.receiver = p
}
```

**Comment by johtoblan** [comment]
Output from the log.Printf was ofcourse omitted.....

> 2020/11/03 15:30:08 *gochan.SendReceiver
> 2020/11/03 15:30:08 *client.ceClient
> 2020/11/03 15:30:08 &{sender:0xc0000b2a20 receiver:0xc0000b2a20}
> 2020/11/03 15:30:08 &{sender:<nil> requester:<nil> receiver:0xc0000bd360 responder:<nil> opener:<nil> outboundContextDecorators:[] invoker:<nil> receiverMu:{state:0 sema:0} eventDefaulterFns:[] pollGoroutines:8}

**Comment by johtoblan** [comment]
Hmm manually sending it through as obj interface{} makes obj.(protocol.Sender) fail with:
```
panic: interface conversion: *gochan.SendReceiver is not protocol.Sender: missing method Send [recovered]
	panic: interface conversion: *gochan.SendReceiver is not protocol.Sender: missing method Send
```
While obj.(protocol.Receiver) works as expected (as commented above)

**Comment by johtoblan** [comment]
Nevermind, was fixed in updated version..
