### ISSUE TITLE
Implement filtering in the mms subscribe functionality.

### ISSUE THREAD

**Issue by johtoblan** [metno/go-mms#127]
As per now, the user has to use argv[1] to filter in the command running after each post. We should consider implementing a filtering done in the mms subscribe command.

**Comment by havardf** [comment]
I would like this feature. E.g something like this.
```
mms subscribe --production-hub testhub  --subject arome_arctic_10m --command /usr/local/bin/best_ever.py
```

I guess most people would like filter only  on subject, so maybe its better to just say that and avoid the complexity with something like --filter="subject=arome_arctic_10m". 

If this sounds ok, I can create a PR for this?

**Comment by havardf** [comment]
@mpejcoch What do you think about this one?

**Comment by mpejcoch** [comment]
This is something we want to do yes. A PR is welcome!
