### ISSUE TITLE
make deps fails to run

### ISSUE THREAD

**Issue by havardf** [metno/go-mms#146]
Seems like the README is not up to date? ```make deps``` fails with: 
```
github.com/metno/go-mms/internal/server imports
        github.com/metno/go-mms/pkg/statik: cannot find module providing package github.com/metno/go-mms/pkg/statik
make: *** [deps] Error 1
```
And I confirmed that there is no ```go-mms/pkg/statik``` directory.

```make build_mms``` works fine.

**Comment by mpejcoch** [comment]
Currently it needs to be run like this
```
RUN make edeps
RUN make statik
RUN make deps
```

see the Dockerfile for reference. We should also use the Dockerfile when running tests on GitHub to reduce the number of build configurations we have.
