### ISSUE TITLE
Send event data downstrem to command

### ISSUE THREAD

**Issue by havardf** [metno/go-mms#150]
The command binary in ```--command``` might need more info than path to dataset. If so, how to get access to any fields in the event?

Some alternatives I can think of:
- By env variable. As in the command callback sets an env variable containing the json string of the event, e.g ```MMS_EVENT={"Product": "foo", ....}.
- By not using command, but piping stdout: ```./mms subscribe --product foo | xargs command_script.py```
- By configuring the command as a job in a config language, and let ./mms generate the command, incl. setting command line args with the requested data from the event.
- By persisting the json file to a tmp file, and then pass the file path to the command. 

Maybe some other alternative? I think using an env variable is the simplest solution though and should be prett straightfoward to use for any command script/binary?

**Comment by havardf** [comment]
@mpejcoch @vkbo What do you think? Is this an approach you are interested in? If so, I could create a PR for a solution with env variables?

**Comment by mpejcoch** [comment]
The env variable solution sounds like the simplest to me and flexible enough too. Happy to get a PR on that, yes!

**Comment by havardf** [comment]
Cool, I will give it a try, but might have to wait until after vacation.

A drawback with this approach though, is that all commands need to do deserialization, which might cause some overhead.

Also,  I think we probably need a second ENV variable: ```MMS_EVENT_VERSION```. So a command can deal with breaking version changes in events.  @mpejcoch Is the version of the mms event format part of the cloud event message?

**Comment by havardf** [comment]
Also, have you thought about adding version to the event json format? Its in the cloud event metadata, but that metadata is not sent to the callback, so its impossible to give that information down to command without hardcoding.

Not sure what the best approach is here.
