### ISSUE TITLE
Fix env vars marshalling of time 

### ISSUE THREAD

**Issue by havardf** [metno/go-mms#170]
Today, a time.Time is marshalled into an env variable with a non-rfc3339 compliant string value.

Solution:
- Custom marshaller with a custom time.Time type?

**Comment by havardf** [comment]
It should not too much work to fork https://github.com/Netflix/go-env, type check for time.Time and have format with RFC3339 instead of using the default time.Time String() method.

We then need to maintain this library, but its not big and has no dependencies. Might be easier than dealing with custom types for time and marshall methods for those.

**Comment by havardf** [comment]
I forked the env vars marshalling package and modified it to handle time.Time with RFC3339:
https://github.com/metno/go-env

@mpejcoch If this sounds ok, I will switch out the dependency now and we should have env vars  in the command formatted with RFC3339 support.

**Comment by mpejcoch** [comment]
It's probably the best solution, what I wonder about is whether there is some process that would help us to get notified about patches upstream and propagate them both to our fork ( I assume that GitHub might have some tools for that) and to go-mms.

**Comment by havardf** [comment]
We can setup a Watch on issues and PR-s for that repo. Not sure if we can get notified for each commit? Or if we even want that.

**Comment by mpejcoch** [comment]
No, not every commit. I was more wondering about major bugs or potential security issues.

**Comment by havardf** [comment]
I set a Watch on that repo for PR, releases and security alerts. Not sure if there more that can be done.
