### ISSUE TITLE
Implement affinity on senda-nats and senda-nats-box-0

### ISSUE THREAD

**Issue by myggen** [metno/go-mms#297]
Like 
senda-nats-0 on datacenter A 
senda-nats-1 on datacenter B
senda-nats-2 on miljodir 

Increase replicas on senda-nats-box-0  to 3  
Handle events.db and nsc userdb syncing between 
instances

Then implement affinity  
senda-nats-box-0 on datacenter A 
senda-nats-box-1 on datacenter B
senda-nats-box-1 on miljodir

**Comment by johtoblan** [comment]
will be closed by merging from staging to prod on the internal s-enda-tjenesterepo (PR 2766)

**Comment by johtoblan** [comment]
Was fixed when we merged from staging to prod on 01.06.
