### ISSUE TITLE
Why use a string for a time variable?

### ISSUE THREAD

**Issue by vegardb** [metno/go-mms#3]
https://github.com/metno/go-mms/blob/99418f4e64dfcc863b68d287a1ac5912fb1081b4/internal/mms/messages.go#L6

Why is not `ReferenceTime` a time.Time? JSON (de)serialization works fine for that datatype, and there you'll get some extra error checking..

**Comment by vkbo** [comment]
I assume it's because the CloudEvents spec we want to use specifies an RFC 3339 formatted string.

**Comment by vegardb** [comment]
https://golang.org/pkg/time/#Time.UnmarshalJSON

:)

**Comment by vkbo** [comment]
I don't know. This looked to me to be part of the message to send, which should conform to the spec, and therefore be a string, no?Also, whatever is passed on to Python should also be a string.

**Comment by havardf** [comment]
Well, the actual answer is that I just hacked that together for demonstration purposes :) We have to properly go through the data model for the product event messages, and setting proper types will be part of that.

**Comment by havardf** [comment]
Fixed in the PR for this issue: #12
