### ISSUE TITLE
Bundle HTML with exec?

### ISSUE THREAD

**Issue by johtoblan** [metno/go-mms#31]
Currently compiling the executable makes it unmovable: 

```
./mmsd
panic: html/template: pattern matches no files: `templates/*`

goroutine 1 [running]:
html/template.Must(...)
	/usr/local/go/src/html/template/template.go:372
main.main()
	/lib/go-mms/cmd/mmsd/main.go:29 +0x2de
```
Such that one must be in the go-mms folder to start the mmsd

**Comment by mpejcoch** [comment]
https://github.com/rakyll/statik looks like a way to go

**Comment by johtoblan** [comment]
@mpejcoch Missing assignee. You on this?
