### ISSUE TITLE
Remove list-production-hubs functionality from go-mms (post)

### ISSUE THREAD

**Issue by mpejcoch** [metno/go-mms#52]
The production hubs will be published in a passive list somewhere in the internal GitLab, we don't need this as part of the application.

**Comment by vkbo** [comment]
I've started working on this, but it's a bit tricky ... Will need to discuss tomorrow.

**Comment by mpejcoch** [comment]
Yes, there are some other parts we might want to restructure in the same change.

**Comment by mpejcoch** [comment]
I have changed the name, we want to eliminate this only for the "post", "subscribe" might still need multiple hubs.
