### ISSUE TITLE
Show test coverage in github repo

### ISSUE THREAD

**Issue by mpejcoch** [metno/go-mms#6]
Use preferably inbuilt tools to minimize dependencies.

**Comment by mpejcoch** [comment]
Well, I tried: https://github.com/metno/go-mms/blob/master/.github/workflows/coverage-badge.yml

It's possible to use actions to generate a badge and then upload it as an artifact, though GitHub doesn't allow to download an artifact as anything else than a zipped file (https://github.com/actions/upload-artifact). And that one can't be easily included in the README.md, so we probably need some external service such as codecov or coveralls.

**Comment by mpejcoch** [comment]
Use the same as in py-mms

**Comment by johtoblan** [comment]
Fixed!
