### ISSUE TITLE
Fix gitignore 

### ISSUE THREAD

**Issue by mpejcoch** [metno/go-mms#7]
It should not be eating directories under internal...

**Comment by johtoblan** [comment]
I do not understand, the .gitignore does not affect my internal/mms folder?

**Comment by vkbo** [comment]
I wrote it, and it shouldn't. The `/` should ensure that it only affects `mms*` in the root directory. The file must of course be updated if we add files that are caught by this simple line, but it should not catch `internal/mms`. It doesn't on my local copy either.

**Comment by mpejcoch** [comment]
Ok, I didn't try myself, came up in a discussion with @havardf, it looked like he didn't include the internal/mms as it didn't show up, perhaps it was a different problem then.
