### ISSUE TITLE
Replace statik with the standard library embedding once it is available

### ISSUE THREAD

**Issue by mpejcoch** [metno/go-mms#73]
https://go.googlesource.com/proposal/+/master/design/draft-embed.md
https://go-review.googlesource.com/c/go/+/243945

Might be part of go 1.16 release.

**Comment by mpejcoch** [comment]
1.16 is out now: https://golang.org/pkg/embed/

**Comment by johtoblan** [comment]
Should this be used instead of Statik then?

**Comment by mpejcoch** [comment]
> Should this be used instead of Statik then?

Yes. We didn't do it yet as we have still been discussing how to use embed in the go app template. Now it's decided, I think, so we can plan to replace it.
