### ISSUE TITLE
Identify possible bottlenecks.

### ISSUE THREAD

**Issue by johtoblan** [metno/go-mms#84]
- Test multiple API-requests.
- How many messages can we send and store per second?
- How many subscribers can we support per message.
- Threading per subscriber?

**Comment by mpejcoch** [comment]
Originally I thought this would be benchmarks, and we should eventually have benchmark in the form
`func Benchmark*(b *testing.B)`

So far it seems we are getting sufficient info via shell while loops and metrics.
