### ISSUE TITLE
NATS subject hardcoded to `mms`

### ISSUE THREAD

**Issue by TAlonglong** [metno/go-mms#99]
I see here https://github.com/metno/go-mms/blob/master/pkg/mms/events.go#L193 that the NATS subject is hardcoded to `mms`. Is this the intention?

It's no big deal, but trying to make a NATS consumer in python I struggled a bit before I got the subject to subscribe for correct.

**Comment by mortenwh** [comment]
Superceded by https://app.zenhub.com/workspaces/s-enda-5e7b1b4acfc5ca185fb6b53c/issues/metno/go-mms/82
